In [36]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE
import openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [37]:
data = pd.read_csv("fulldata.csv")

In [38]:
le= LabelEncoder()
df =np.array(data)
X = df[:,:-1]
y =df[:,-1]
sm = SMOTE(sampling_strategy='minority', random_state=42)
X, y= sm.fit_resample(X, y)
y_encoded=le.fit_transform(y)

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y_encoded, random_state=1, stratify=y)

In [40]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaler = scaler.fit(x_train)
X_train_scaled = X_scaler.transform(x_train)
X_test_scaled = X_scaler.transform(x_test)

In [41]:
model = LogisticRegression(
    solver= 'saga',
    penalty="l2",
    max_iter=1,  # local epoch
    warm_start=True,  # prevent refreshing weights when fitting
)

In [42]:
model.fit(X_train_scaled, y_train)

D:\Anaconda\envs\flower\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(max_iter=1, solver='saga', warm_start=True)

In [43]:
preds = model.predict(X_test_scaled)

In [44]:
accuracy_score(y_test, preds)

0.7879655323499343

In [45]:
confusion_matrix(y_test, preds)

array([[13258,  3859],
       [ 3400, 13718]], dtype=int64)

In [46]:
# Print the imbalanced classification report
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.80      0.77      0.79     17117
           1       0.78      0.80      0.79     17118

    accuracy                           0.79     34235
   macro avg       0.79      0.79      0.79     34235
weighted avg       0.79      0.79      0.79     34235



In [1]:
import pickle
filename = 'generalized_model.sav'
pickle.dump(model, open(f"model/{filename}", 'wb'))

NameError: name 'model' is not defined

In [6]:
c1_model.intercept_

array([0.09802168])

In [12]:
import numpy as np
c1_model.coef_ = np.zeros((2, 86))

In [13]:
c1_model.coef_

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.]])

In [15]:
import glob
import os.path
import pickle


folder_path = f'model/agg_models'
file_type = r'\*.sav'
files = glob.glob(folder_path + file_type)
max_file = max(files, key=os.path.getctime)
last_updated_model = max_file
latest_model = pickle.load(open(f'{last_updated_model}', 'rb'))

    

In [7]:
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression(
        solver= 'saga',
        penalty="l2",
        max_iter=1,  # local epoch
        warm_start=True,  # prevent refreshing weights when fitting
    )

In [16]:
latest_model.classes_

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
model1.classes_

AttributeError: 'LogisticRegression' object has no attribute 'classes_'